---
title: "Economically Active Population Survey By Gender | Korea 2020-2021"
author: "Han Gang Magazine"
date: "5/15/2021"
output: html_document
---

*Official unemployment rates by Gender, based on 4 week job search period*

*Data: [Economic Active Survey from Korean Statistical Information Service (KOSIS)](https://kosis.kr/statisticsList/statisticsListIndex.do?parentId=D.1&vwcd=MT_ZTITLE&menuId=M_01_01)

```{r}
library(ggplot2)
library(tidyr)
library(RColorBrewer)
library(ggsci)
# load econ_active
econ_active <- read.csv("econ_active.csv")
colnames(econ_active)[colnames(econ_active) == "ï..Month"] <- "Month" #change colname
econ_active
# commit x-bar to prevent alphabetical reordering
econ_active$Month <- factor(econ_active$Month, levels = econ_active$Month)
# econ_active plot
econ_active %>%
  gather("Gender", "Population", -Month) %>%
  ggplot(aes(x= Month, y = Population, fill = Gender)) +
  geom_bar(width = 0.7, position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(title = "Economically Active Population By Gender | Korea 2020 - 2021", 
       x = "Month", y = "Population (thousands)") + 
  theme(plot.title = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")
  ) +
  coord_cartesian(ylim = c(5000, 30000)) +
  scale_y_continuous(limits = c(0, 30000), breaks=seq(0, 30000, 5000)) +
  scale_fill_manual(values = c("Female" = "#ff69b4", 
                               "Male" = "#00bfff",
                               "All" = "#90ee90"))
```

```{r}
# employed csv
employed <- read.csv("Employed.csv")
colnames(employed)[colnames(employed) == "ï..Month"] <- "Month" #change colname
employed
# commit x-bar to prevent alphabetical reordering
employed$Month <- factor(employed$Month, levels = employed$Month)
# econ_active plot
employed %>%
  gather("Gender", "Population", -Month) %>%
  ggplot(aes(x= Month, y = Population, fill = Gender)) +
  geom_bar(width = 0.7, position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(title = "Employed Population By Gender | Korea 2020 - 2021", 
       x = "Month", y = "Population (thousands)") + 
  theme(plot.title = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")
  ) +
  coord_cartesian(ylim = c(5000, 30000)) +
  scale_y_continuous(limits = c(0, 30000), breaks=seq(0, 30000, 5000)) +
  scale_fill_manual(values = c("Female" = "#ff69b4", 
                               "Male" = "#00bfff",
                               "All" = "#90ee90"))
```

```{r}
# unemployed csv
unemployed <- read.csv("Unemployed.csv")
colnames(unemployed)[colnames(unemployed) == "ï..Month"] <- "Month" #change colname
unemployed
# commit x-bar to prevent alphabetical reordering
unemployed$Month <- factor(unemployed$Month, levels = unemployed$Month)
# econ_active plot
unemployed %>%
  gather("Gender", "Population", -Month) %>%
  ggplot(aes(x= Month, y = Population, fill = Gender)) +
  geom_bar(width = 0.7, position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(title = "Unemployed Population By Gender | Korea 2020 - 2021", 
       x = "Month", y = "Population (thousands)") + 
  theme(plot.title = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")
  ) + 
  coord_cartesian(ylim = c(300,1600)) +
  scale_y_continuous(limits = c(0, 1600), breaks=seq(0, 1600, 100)) +
  scale_fill_manual(values = c("Female" = "#ff69b4", 
                               "Male" = "#00bfff",
                               "All" = "#90ee90"))
```

```{r}
# perc participation csv
participation <- read.csv("perc_participation.csv")
colnames(participation)[colnames(participation) == "ï..Month"] <- "Month" #change colname
participation
# commit x-bar to prevent alphabetical reordering
participation$Month <- factor(participation$Month, levels = participation$Month)
# econ_active plot
participation %>%
  gather("Gender", "Percentage", -Month) %>%
  ggplot(aes(x= Month, y = Percentage, fill = Gender)) +
  geom_bar(width = 0.7, position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage Workforce Participation By Gender | Korea 2020 - 2021", 
       x = "Month", y = "Percentage") + 
  theme(plot.title = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")
  ) + 
  coord_cartesian(ylim = c(45, 75)) +
  scale_y_continuous(breaks=seq(45, 75, 5), labels = scales::percent_format(scale = 1)) +
  scale_fill_manual(values = c("Female" = "#ff69b4", 
                               "Male" = "#00bfff",
                               "All" = "#90ee90"))
```

```{r}
# unemployed% csv
unemployed_perc <- read.csv("Unemployed%.csv")
colnames(unemployed_perc)[colnames(unemployed_perc) == "ï..Month"] <- "Month" #change colname
unemployed_perc
# commit x-bar to prevent alphabetical reordering
unemployed_perc$Month <- factor(unemployed_perc$Month, levels = unemployed_perc$Month)
# econ_active plot
unemployed_perc %>%
  gather("Gender", "Percentage", -Month) %>%
  ggplot(aes(x= Month, y = Percentage, fill = Gender)) +
  geom_bar(width = 0.7, position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage Unemployment By Gender | Korea 2020 - 2021", 
       x = "Month", y = "Percentage") + 
  theme(plot.title = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")
  ) + 
  coord_cartesian(ylim = c(3, 7)) +
  scale_y_continuous(breaks = seq(3, 7, 0.5), labels = scales::percent_format(scale = 1)) +
  scale_fill_manual(values = c("Female" = "#ff69b4", 
                               "Male" = "#00bfff",
                               "All" = "#90ee90"))
```
```{r}
# Employed% csv
employed_perc <- read.csv("Employed%.csv")
colnames(employed_perc)[colnames(employed_perc) == "ï..Month"] <- "Month" #change colname
employed_perc
# commit x-bar to prevent alphabetical reordering
employed_perc$Month <- factor(employed_perc$Month, levels = employed_perc$Month)
# econ_active plot
employed_perc %>%
  gather("Gender", "Percentage", -Month) %>%
  ggplot(aes(x= Month, y = Percentage, fill = Gender)) +
  geom_bar(width = 0.7, position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage Employment By Gender | Korea 2020 - 2021", 
       x = "Month", y = "Percentage") + 
  theme(plot.title = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")
  ) +
  coord_cartesian(ylim = c(48, 71)) +
  scale_y_continuous(breaks = seq(48, 71, 5), labels = scales::percent_format(scale = 1)) +
  scale_fill_manual(values = c("Female" = "#ff69b4", 
                               "Male" = "#00bfff",
                               "All" = "#90ee90"))
```

